import { ApiProperty } from '@nestjs/swagger';
import {
  Column,
  CreateDateColumn,
  Entity,
  ManyToOne,
  PrimaryGeneratedColumn,
} from 'typeorm';
import { Order } from './orders.entity';
import { DeliveryStatus } from '../enums/delivery-status.enum';
import { TrackingEventActorType } from '../enums/tracking-event-actor-type.enum';

@Entity('order_tracking_events')
export class OrderTrackingEvent {
  @ApiProperty({
    description: 'Unique tracking event identifier',
    example: '550e8400-e29b-41d4-a716-446655440000',
  })
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @ManyToOne(() => Order, (order) => order.trackingEvents, {
    onDelete: 'CASCADE',
  })
  order: Order;

  @ApiProperty({
    description: 'Delivery status captured in this event',
    enum: DeliveryStatus,
    example: DeliveryStatus.OUT_FOR_DELIVERY,
  })
  @Column({ type: 'varchar', length: 32 })
  deliveryStatus: DeliveryStatus;

  @ApiProperty({
    description: 'Carrier tracking number at this event',
    required: false,
    nullable: true,
  })
  @Column({ type: 'varchar', length: 128, nullable: true })
  trackingNumber?: string | null;

  @ApiProperty({
    description: 'Shipping carrier at this event',
    required: false,
    nullable: true,
  })
  @Column({ type: 'varchar', length: 128, nullable: true })
  shippingCarrier?: string | null;

  @ApiProperty({
    description: 'Tracking URL at this event',
    required: false,
    nullable: true,
  })
  @Column({ type: 'varchar', length: 2048, nullable: true })
  trackingUrl?: string | null;

  @ApiProperty({
    description: 'Location captured in this event',
    required: false,
    nullable: true,
  })
  @Column({ type: 'varchar', length: 160, nullable: true })
  currentLocation?: string | null;

  @ApiProperty({
    description: 'Tracking note captured in this event',
    required: false,
    nullable: true,
  })
  @Column({ type: 'varchar', length: 255, nullable: true })
  trackingNote?: string | null;

  @ApiProperty({
    description: 'When this event happened',
    example: '2026-03-08T19:20:00.000Z',
  })
  @Column({ type: 'timestamptz' })
  eventAt: Date;

  @ApiProperty({
    description: 'Who generated the event',
    enum: TrackingEventActorType,
    example: TrackingEventActorType.ADMIN,
  })
  @Column({ type: 'varchar', length: 32 })
  actorType: TrackingEventActorType;

  @ApiProperty({
    description: 'Actor user id when event is generated by an admin',
    required: false,
    nullable: true,
    example: 1,
  })
  @Column({ type: 'int', nullable: true })
  actorUserId?: number | null;

  @CreateDateColumn()
  createdAt: Date;
}
